### ISSUE TITLE
API: Create new comment

### ISSUE THREAD

**Issue by steveleee** [steveleee/dispatch#3]
* Method: POST
* `tweet/:tweet_id/comment`
* Posts a response to the tweet with the tweet ID
* Check if Tweet exists before creating the response
* POST Body:
```
{
    tweet_id: Int,
    body: String
}
```

**Comment by steveleee** [comment]
@dwb264 I renamed the `response` parameter in the JSON to `body`, think it makes more sense.

**Comment by dwb264** [comment]
Doesn't ```author_id``` also need to be part of the POST body?

**Comment by steveleee** [comment]
You can retrieve the user from the request object, check out how I did it for the dispatch method

**Comment by dwb264** [comment]
Ok, figured that out, thanks. For that matter, does ```tweet_id``` need to be part of the POST body (since it's already in the URL)?

**Comment by steveleee** [comment]
You’re right, doesn’t need it
